# Generated by Django 2.2.27 on 2023-02-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_auto_20221010_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='town',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='town',
            old_name='lng',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
