# Generated by Django 2.2.27 on 2022-10-15 14:02

from django.db import migrations, models
import django.db.models.deletion
import travels.enums
import travels.models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_auto_20221010_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeConditionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='town',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='town',
            old_name='lng',
            new_name='longitude',
        ),
        migrations.AddField(
            model_name='badge',
            name='type',
            field=models.CharField(choices=[('INDIVIDUAL', 'IND'), ('PLATFORM', 'PLT')], default=travels.enums.BadgeType('IND'), max_length=20),
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='condition',
            field=models.ForeignKey(default=travels.models.BadgeConditionGroup.get_default_condition, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='travels.BadgeConditionGroup'),
        ),
    ]
